/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingstoresystem;

/**
 *
 * @author Asus
 */
public class StoreTransactionFrame extends javax.swing.JFrame {
    
    // --- CART VARIABLES ---
    private int[] cartQuantities = new int[SwingStoreSystem.PRODUCT_COUNT];
    private double currentTotalCost = 0.0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StoreTransactionFrame.class.getName());

    /**
     * Creates new form StoreTransactionFrame
     */
    public StoreTransactionFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        

            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Product = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JLabel();
        Order = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        Logs = new javax.swing.JButton();
        Inventory = new javax.swing.JButton();
        Complete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Product.setText("  Select Product");

        ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Sugar ", "Coffee", "Milk" }));
        ComboBox.addActionListener(this::ComboBoxActionPerformed);

        Quantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Quantity.setText("     Quantity");

        Order.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Order.setText("Place Order");
        Order.addActionListener(this::OrderActionPerformed);

        TextField.addActionListener(this::TextFieldActionPerformed);

        Logs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logs.setText("View Logs");
        Logs.addActionListener(this::LogsActionPerformed);

        Inventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inventory.setText("Inventory ");
        Inventory.addActionListener(this::InventoryActionPerformed);

        Complete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Complete.setText("Checkout");
        Complete.addActionListener(this::CompleteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Order)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Complete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logs, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Complete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        // TODO add your handling code here:
        
        new InventoryFrame().setVisible(true);
        this.dispose(); // Closes the transaction frame
    }//GEN-LAST:event_InventoryActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void LogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogsActionPerformed
        // TODO add your handling code here:
        
        new TransactionLogsFrame().setVisible(true);
        this.dispose(); // Closes the transaction frame
    }//GEN-LAST:event_LogsActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        
      try {
            int selectedIndex = ComboBox.getSelectedIndex();
            String qtyString = TextField.getText();
            
            if (qtyString.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a quantity.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int qty = Integer.parseInt(qtyString);

            if (qty <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0!", "Invalid Quantity", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if what is already in their cart + what they are adding now exceeds stock
            int totalDesiredQty = cartQuantities[selectedIndex] + qty;
            if (totalDesiredQty > SwingStoreSystem.inventoryStock[selectedIndex]) {
                javax.swing.JOptionPane.showMessageDialog(this, "Insufficient stock! Only " + SwingStoreSystem.inventoryStock[selectedIndex] + " total units left.", "Stock Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 1. Compute Subtotal
            double price = SwingStoreSystem.productPrices[selectedIndex];
            double subtotal = price * qty;
            
            // 2. Add to Cart Array & Update Total
            cartQuantities[selectedIndex] += qty;
            currentTotalCost += subtotal;

            // 3. Show Subtotal Popup
            String productName = SwingStoreSystem.productNames[selectedIndex];
            javax.swing.JOptionPane.showMessageDialog(this, "Added to cart: " + productName + " (x" + qty + ")\nSubtotal: ₱" + subtotal, "Item Added", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            TextField.setText(""); // Clear text field for the next item

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid whole number.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_OrderActionPerformed

    private void CompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteActionPerformed
        // TODO add your handling code here:
        if (currentTotalCost == 0.0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Your cart is empty! Please add items first.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder receipt = new StringBuilder("--- FINAL RECEIPT ---\n\n");

        // Loop through the cart array
        for (int i = 0; i < SwingStoreSystem.PRODUCT_COUNT; i++) {
            if (cartQuantities[i] > 0) { // If they bought this specific item
                int qty = cartQuantities[i];
                double itemTotal = SwingStoreSystem.productPrices[i] * qty;
                
                // 1. Deduct from Global Inventory
                SwingStoreSystem.inventoryStock[i] -= qty;
                
                // 2. Save to Global Transaction Logs
                if (SwingStoreSystem.transactionCount < SwingStoreSystem.MAX_TRANSACTIONS) {
                    int logIdx = SwingStoreSystem.transactionCount;
                    SwingStoreSystem.logProductNames[logIdx] = SwingStoreSystem.productNames[i];
                    SwingStoreSystem.logQuantities[logIdx] = qty;
                    SwingStoreSystem.logTotals[logIdx] = itemTotal;
                    
                    SwingStoreSystem.transactionCount++; 
                }

                receipt.append(SwingStoreSystem.productNames[i]).append(" (x").append(qty).append(") = ₱").append(itemTotal).append("\n");
                
                // 3. Clear the cart for this item
                cartQuantities[i] = 0; 
            }
        }

        // Add Total Cost
        receipt.append("\n---------------------------\n");
        receipt.append("GRAND TOTAL: ₱").append(currentTotalCost);

        // Show Final Receipt Popup
        javax.swing.JOptionPane.showMessageDialog(this, receipt.toString(), "Transaction Complete", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Reset the total cost for the next customer
        currentTotalCost = 0.0;
    }//GEN-LAST:event_CompleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StoreTransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Complete;
    private javax.swing.JButton Inventory;
    private javax.swing.JButton Logs;
    private javax.swing.JButton Order;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField TextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
